font:
  default: ""
  description:
    en: "Select a new font from <a href='https://fonts.google.com'>Google Font</a>. Depending on the chosen one, you can further customize it, for example <b>Sarabun:300,400,500</b>  If not set the default font will be applied."
font_family:
  default: ""
  description:
    en: "Specifies the font to use. If not set the default font will be applied."
hljs_light:
  default: "#333"
  description:
    en: "Light theme. Choose the color for text." 
code_light:
  default: "#333"
  description:
    en: "Light theme. Choose the color for code."  
code_background_light:
  default: "#f8f8f8"
  description:
    en: "Light theme. Choose the background color for code."      
comment_light:
  default: "#998"
  description:
    en: "Light theme. Choose the color for comment and doctag." 
title_light:
  default: "#d14"
  description:
    en: "Light theme. Choose the color for title, name and meta." 
string_light:
  default: "#d14"
  description:
    en: "Light theme. Choose the color for string." 
number_light:
  default: "#099"
  description:
    en: "Light theme. Choose the color for number." 
keyword_light:
  default: "#333"
  description:
    en: "Light theme. Choose the color for keyword, subst, request, and status." 
class_title_light:
  default: "#458"
  description:
    en: "Light theme. Choose the color for the title inside the class element." 
tag_light:
  default: "#000080"
  description:
    en: "Light theme. Choose the color for tag." 
attribute_light:
  default: "#008080"
  description:
    en: "Light theme. Choose the color for attribute." 
symbol_light:
  default: "#990073"
  description:
    en: "Light theme. Choose the color for symbol." 
hljs_dark:
  default: "#f8f8f8"
  description:
    en: "Dark theme. Choose the color for text."
code_dark:
  default: "#f8f8f8"
  description:
    en: "Dark theme. Choose the color for code."      
code_background_dark:
  default: "#333"
  description:
    en: "Dark theme. Choose the background color for code."      
comment_dark:
  default: "#bba"
  description:
    en: "Dark theme. Choose the color for comment."
title_dark:
  default: "#f99"
  description:
    en: "Dark theme. Choose the color for title, name and meta." 
string_dark:
  default: "#f99"
  description:
    en: "Dark theme. Choose the color for string."
number_dark:
  default: "#aff"
  description:
    en: "Dark theme. Choose the color for number."    
keyword_dark:
  default: "#f8f8f8"
  description:
    en: "Dark theme. Choose the color for keyword, subst, request and status."
class_title_dark:
  default: "#9ae"
  description:
    en: "Dark theme. Choose the color for the title inside the class element."
tag_dark:
  default: "#99f"
  description:
    en: "Dark theme. Choose the color for tag." 
attribute_dark:
  default: "#0ee"
  description:
    en: "Dark theme. Choose the color for attribute."
symbol_dark:
  default: "#fbe"
  description:
    en: "Dark theme. Choose the color for symbol."    
    
