comment_light:
  default: "#998"
  description:
    en: "Light theme. Choose the color for comments" 
comment_dark:
  default: "#bba"
  description:
    en: "Dark theme. Choose the color for comments."
title_light:
  default: "#d14"
  description:
    en: "Light theme. Choose the color for titles and names." 
title_dark:
  default: "#f99"
  description:
    en: "Dark theme. Choose the color for titles and names." 
string_light:
  default: "#d14"
  description:
    en: "Light theme. Choose the color for strings." 
string_dark:
  default: "#f99"
  description:
    en: "Dark theme. Choose the color for strings."
number_light:
  default: "#099"
  description:
    en: "Light theme. Choose the color for numbers." 
number_dark:
  default: "#aff"
  description:
    en: "Dark theme. Choose the color for numbers."    
keyword_light:
  default: "#333"
  description:
    en: "Light theme. Choose the color for keywords." 
keyword_dark:
  default: "#f8f8f8"
  description:
    en: "Dark theme. Choose the color for keywords."
class_title_light:
  default: "#458"
  description:
    en: "Light theme. Choose the color for titles inside the class element." 
class_title_dark:
  default: "#9ae"
  description:
    en: "Dark theme. Choose the color for titles inside the class element."
tag_light:
  default: "#000080"
  description:
    en: "Light theme. Choose the color for tags." 
tag_dark:
  default: "#99f"
  description:
    en: "Dark theme. Choose the color for tags." 
attribute_light:
  default: "#008080"
  description:
    en: "Light theme. Choose the color for attributes." 
attribute_dark:
  default: "#0ee"
  description:
    en: "Dark theme. Choose the color for attributes."
symbol_light:
  default: "#990073"
  description:
    en: "Light theme. Choose the color for symbols." 
symbol_dark:
  default: "#fbe"
  description:
    en: "Dark theme. Choose the color for symbols."    
